GradeTracker/Controllers/GradebookController.cs
using GradeTracker.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json.Linq;
using System.Web.Script.Serialization;

namespace GradeTracker.Controllers
{
    public class GradebookController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

		/****************** DATABASE ACCESS FUNCTIONS ********************/

		// Perform a query to find specific CourseModel objects in the DB.
		private List<CourseModel> QueryCourses(string query)
        {
            var result = db.CourseModels.SqlQuery(query);
            return result.ToList();
        }

		// Perform a query to find specific SemesterModel objects in the DB.
        private List<SemesterModel> QuerySemesters(string query)
        {
            var result = db.SemesterModels.SqlQuery(query);
            return result.ToList();
        }

		// Get all SemesterModels associated with the currently logged in user.
		private List<SemesterModel> GetSemestersForStudent()
		{
			var result = db.SemesterModels.SqlQuery(String.Format("SELECT * FROM SemesterModels WHERE assocUserId='{0}'", User.Identity.GetUserId()));
			return result.ToList();
		}

		// Get the SemesterModel object that a CourseModel object is associated with.
        private SemesterModel GetSemesterForCourse(CourseModel course)
        {
            var result = db.SemesterModels.SqlQuery(String.Format("Select * FROM SemesterModels WHERE semesterId={0}", course.assocSemesterId));
            return result.First();
        }

		// Get the Semester model object that is associated with the semesterID.
		private SemesterModel GetSemesterById(int semesterId)
		{
			var result = db.SemesterModels.SqlQuery(String.Format("SELECT * FROM SemesterModels WHERE semesterId={0}", semesterId));
			return result.First();
		}

		// Checks the number of semesters that exist matching the passed semesterId
		private int SemesterCount(int semesterId)
		{
			var result = db.SemesterModels.SqlQuery(String.Format("SELECT * FROM SemesterModels WHERE semesterId={0}", semesterId));
			return result.Count();
		}

		// Get a CourseModel object with a courseId that matches the function argument.
        private CourseModel GetCourseById(int courseId)
        {
            var result = db.CourseModels.SqlQuery(String.Format("SELECT * FROM CourseModels where courseId={0}", courseId));
            return result.First();
        }

		// Checks the number of courses matching the passed courseId
		private int CourseCount(int courseId)
		{
			var result = db.CourseModels.SqlQuery(String.Format("SELECT * FROM CourseModels WHERE courseId={0}", courseId));
			return result.Count();
		}

		// Get all CourseModel objects associated with a specific semesterId
		private List<CourseModel> GetCoursesForSemester(int semesterId)
		{
			var result = db.CourseModels.SqlQuery(String.Format("SELECT * FROM CourseModels where assocSemesterId={0}", semesterId));
			return result.ToList();
		}

		// Get all WorkItemModels associated with a specific CourseModel object.
        private List<WorkItemModel> GetWorkItemsForCourse(CourseModel course)
        {
            var result = db.WorkItemModels.SqlQuery(String.Format("SELECT * FROM WorkItemModels WHERE assocCourseId={0}", course.courseId));
            return result.ToList();
        }

		// Returns the number of work items with a matching work item id.
		private int WorkItemCount(int id)
		{
			var result = db.WorkItemModels.SqlQuery(String.Format("SELECT * FROM WorkItemModels WHERE id={0}",id));
			return result.Count();
		}

		// Get all CategoryWeights associated with a given CourseModel object.
        private List<CategoryWeight> GetCategoryWeightsForCourse(CourseModel course)
        {
            var result = db.CategoryWeights.SqlQuery(String.Format("SELECT * FROM CategoryWeights WHERE assocCourseId={0}", course.courseId));
            return result.ToList();
        }

		// Get a CategoryWeight object with an id matching the function argument.
		private CategoryWeight GetCategoryWeight(int id)
		{
			var result = db.CategoryWeights.SqlQuery(String.Format("SELECT * FROM CategoryWeights WHERE categoryId={0}", id));
			return result.First();
		}

		// Get a CategoryWeight object for a course with a specific name.
		private CategoryWeight GetCategoryWeight(string categoryName, int courseId)
		{
			var result = db.CategoryWeights.SqlQuery(String.Format("SELECT * FROM CategoryWeights WHERE assocCourseId={0} AND categoryName='{1}'", courseId, categoryName));
			return result.First();
		}

		// Get a WorkItemModel with an id that matches the function argument.
		private WorkItemModel GetWorkItemById(int id)
		{
			var result = db.WorkItemModels.SqlQuery(String.Format("SELECT * from WorkItemModels WHERE id={0}", id));
			return result.First();
		} 

        /*****************************************************************/


        /**************************AJAX CALLS*****************************/

		/*
		 * Get a list of the semester GPAs for all semesters belonging to the currently
		 * logged in user. Return them as a Json object.
		 */ 
		[HttpGet]
		public JsonResult GetAllSemesterGPAs()
		{
			List<SemesterModel> semesters = GetSemestersForStudent();
			var result = new List<Object>();

			foreach(SemesterModel semester in semesters)
			{
				var gpaJson = new JavaScriptSerializer().Serialize(GetSemesterGPA(semester.semesterId).Data);
				var gpa = JObject.Parse(gpaJson)["semesterGpa"].ToString();
				result.Add(new {semesterId = semester.semesterId, gpa =  Double.Parse(gpa)});
			}
			return Json(result, JsonRequestBehavior.AllowGet);
		}

		/*
		 * Get the semester gpa for a specific semester.
		 */ 
		[HttpGet]
		public JsonResult GetSemesterGPA(int semesterId) {
			GradeTracker.Models.BusinessLogic.GradeComputation gradeComp = new Models.BusinessLogic.GradeComputation(db);
			List<CourseModel> courses = GetCoursesForSemester(semesterId);
			double semesterGpa = gradeComp.CalculateSemesterGPA(courses);
			return Json(new {semesterGpa = semesterGpa }, JsonRequestBehavior.AllowGet);
		}

		/*
		 * Uses a GradeComputation obeject to get the overall weighted grade for a courseId.
		 * Retrusn the grade to the view as a Json object.
		 */ 
		[HttpGet]
		public JsonResult GetWeightedGrade(int courseId)
		{
			Models.BusinessLogic.GradeComputation gradeComp = new Models.BusinessLogic.GradeComputation(db);
			double grade = gradeComp.GetWeightedCourseGrade(courseId);
			return Json(new {weightedGrade = grade}, JsonRequestBehavior.AllowGet);
		}

		/*
		 * Uses a GradeComputation object to get the overall grade for a specific weight
		 * category in a specific course. Returns the result in a Json object.
		 */ 
		[HttpPost]
		public JsonResult GetOverallCategoryGrade(int courseId, string categoryName)
		{
			Models.BusinessLogic.GradeComputation gradeComp = new Models.BusinessLogic.GradeComputation(db);
			CategoryWeight weight = GetCategoryWeight(categoryName, courseId);
			double categoryGrade = gradeComp.GetCategoryOverallGrade(courseId, categoryName);
			return Json(new {categoryGrade = categoryGrade, categoryId = weight.categoryId}, JsonRequestBehavior.AllowGet);
		}

		/*
		 * Checks the database to see if a semester exists with the given semseterId. Used to prevent adding
		 * courses to a semester that has been deleted.
		 */ 
		[HttpGet]
		public JsonResult SemesterExists(int semesterId)
		{
			if(SemesterCount(semesterId) != 0)
			{
				/*
				if(GetSemesterById(semesterId).assocUserId != User.Identity.GetUserId()) {
					return Json(new {result = "Invalid"}, JsonRequestBehavior.AllowGet);
				}
				*/
				return Json(new {result = true}, JsonRequestBehavior.AllowGet);
			}	
			return Json(new {result = false},JsonRequestBehavior.AllowGet);
		}


		/*
		 * Completely delete a semester, including all associated models. 
		 */ 
		[HttpPost]
		public JsonResult DeleteSemester(int semesterId)
		{
			SemesterModel semester = GetSemesterById(semesterId);
			List<CourseModel> associatedCourses = GetCoursesForSemester(semesterId);
			try
			{
				foreach(CourseModel course in associatedCourses)
				{
					DeleteCourse(course.courseId);
				}
				if(db.SemesterModels.Remove(semester) != null)
				{
					db.SaveChanges();
					return Json(new {result = true});
				}
			}
			catch(Exception ex)
			{
				return Json(new {result = false});
			}
			return Json(new {result = false});
			
		}

		/*
		 * Delete all CourseModels/CategoryWeights/WorkItemModels associated with the given semester.
		 */ 
		[HttpPost]
		public JsonResult ResetSemester(int semesterId) 
		{
			SemesterModel semester = GetSemesterById(semesterId);
			List<CourseModel> associatedCourses = GetCoursesForSemester(semesterId);
			try
			{
				foreach(CourseModel course in associatedCourses)
				{
					DeleteCourse(course.courseId);
				}
				return Json(new {result = true});
			}
			catch(Exception ex)
			{
				return Json(new {result = false});
			}
		}

		/*
		 * Checks if the course exists in the database. Returns a JsonResult object.
		 */ 
		[HttpGet]
		public JsonResult CourseExists(int courseId)
		{
			if(CourseCount(courseId) != 0)
			{
				return Json(new {result = true}, JsonRequestBehavior.AllowGet);
			}
			return Json(new {result = false}, JsonRequestBehavior.AllowGet);
		}

		/*
		 * Delete a specific course from the databases, as well as the WorkItemModels
		 * and CategoryWeight objects that are associated with that course.
		 */ 
		[HttpPost]
		public JsonResult DeleteCourse(int courseId)
		{
			CourseModel course = GetCourseById(courseId);
			List<CategoryWeight> associatedWeights = GetCategoryWeightsForCourse(course);
			List<WorkItemModel> associatedWorkItems = GetWorkItemsForCourse(course);

			try
			{
				if(DeleteAllWeights(course))
				{
					if(DeleteAllWorkItems(course))
					{

GradeTracker/Controllers/HomeController.cs
using GradeTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Data.Entity;

namespace GradeTracker.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			// If the user is not logged in, display the generic homepage.
			if (!User.Identity.IsAuthenticated)
			{
				return View();
			}

			//If the user IS logged in, display the user specific homepage.
			ApplicationDbContext db = new ApplicationDbContext();
			StudentModel student = db.Students.Find(User.Identity.GetUserId());

			// Send user to the logged in homepage, pass the student object to the view for use.
			return View("AccountHome", student);
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}
		
		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}

		public ActionResult FinalGradeCalculator()
		{
			return View();
		}

		public ActionResult Invalid()
		{
			return View();
		}

		/*
		 * Display the "Learn More" view.
		 */ 
		public ActionResult LearnMore()
		{
			return View();
		}

		public JsonResult GetFinalGradeNeeded(double currentGrade, double gradeWanted, double finalWeight)
		{
			Models.BusinessLogic.GradeComputation gradeComp = new Models.BusinessLogic.GradeComputation();
			double finalGradeNeeded = gradeComp.CalcGradeNeededOnFinal(currentGrade, gradeWanted, finalWeight);
			return Json(new {gradeNeeded = finalGradeNeeded}, JsonRequestBehavior.AllowGet);
		}
	}
}

GradeTracker/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>About Personal Gradebook</h2>
<div class="row">
    <div class="col-md-8">
        <hr />
        <p>I made Personal Gradebook a free web application to help students keep track of their weighted grades. 
        It always drove me crazy when using grading platforms like Blackboard and Canvas that the grade shown
        online typically wasn't your actual weighted grade. It was up to the instructor of the course to set
        up the weight categories and input the assignment grades correctly, which usually didn't happen. Because
        of this the grade you see online is typically a simple points earned divided by points possibie score, which
        isn't very useful in a weighted grade course.
        </p>
        <p>
        Personal Gradebook allows the student to input their own custom weight categories for a course, then add assignments
        to those categories. It presents the student with their current weighted grade as opposed to unweighted grade.
        I also wanted to give students the option to have a final grade calculator that can calcuate what score they need
        on their final exam without having to do your own weighted grade calculation.
        It's free, super easy to use and really helpful.
        </p>
        <p>
            - Scott Krohn
        </p>
    </div>
</div>

GradeTracker/Views/Home/AccountHome.cshtml
@{
    ViewBag.Title = "AccountHome";
}

<div class="row add-margin-top">
    <div class="col-md-6">
        <h2>@Model.firstName @Model.lastName's Gradebook</h2>
        <h4>@Model.school</h4>
    </div>
</div>
<hr />

<!-- TODO: Show the GPA for each course in the list.  -->
<div class="row">
    <div class="col-lg-7">
        <div class="row">
            <!-- List Title -->
            <div class="col-md-9 add-margin-bottom">
                <h3 style="display: inline;">Semesters</h3>
            </div>

            <div class="col-md-3">
                <a href="@Url.Action("AddSemester", "Gradebook", Model)" class="btn btn-primary "><span class="glyphicon glyphicon-plus"></span> Add Semester</a>
            </div>
        </div>
            
        <div class="list-group semesterGroup">
             <!-- Get all of the semesters associated with the logged in student and display them as a list-group. -->
            @{
                var db = new GradeTracker.Models.ApplicationDbContext();
                var semesters = db.SemesterModels.SqlQuery(String.Format("SELECT * FROM SemesterModels WHERE assocUserId='{0}'", Model.assocUserAccountId));
                foreach(var semester in semesters) {
                    <div class="semesterEntry col-md-12"><a href="@Url.Action("Courses", "Gradebook", semester)" class="list-group-item">@semester.termName @semester.termYear<span class="pull-right" id=@semester.semesterId></span></a></div>
                }
                <div class="col-md-12 add-margin-top" id="noSemestersSection" hidden>
                    <p class="text-warning">You currently don't have any semesters added to your gradebook. Click the "Add Semester" button above to get started.</p>
                </div>
            }        
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        if ($('.semesterEntry').length == 0) {
            $('#noSemestersSection').show();
        }
        loadSemesterGPAs();
    });

    /*
    * Perform ajax call to Gradebook controller to get a list of the current user's
    * GPAs for each semester. Display them in the list of semesters.
    */
    function loadSemesterGPAs() {
        $.ajax({
            url: "/Gradebook/GetAllSemesterGPAs",
            type: "GET",
            datatype: "json",
            success: function (data) {
                $.each(data, function (index, element) {
                    var gpa = (element.gpa).toFixed(2);
                    // If the GPA isn't zero (meaning no classes have grades) display it.
                    if (gpa != 0) {
                        $('#' + element.semesterId).html("GPA: " + gpa);
                    }
                    // If the GPA == 0, display N/A instead of GPA: 0.00
                    else {
                        $('#' + element.semesterId).html("GPA: N/A");
                    }
                });
            },
            error: function (data) {
                alert("ERROR");
            }
        });
    }

</script>

GradeTracker/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<h2>Contact Us</h2>
<hr />
<div class="row">
    <div class="col-md-6">
        <p>If you have any questions or if you notice any bugs please send me a message below.</p>
        <address>
            <strong>Email:</strong>   <a href="mailto:info@personalgradebook.com">info@personalgradebook.com</a><br />
        </address>
    </div>
</div>

GradeTracker/Views/Home/FinalGradeCalculator.cshtml
@{
    ViewBag.Title = "FinalGradeCalculator";
}


<div class="row add-margin-top">
    <div class="col-md-6">
        <h2>Final Grade Calculator</h2>
        <h4>Calculate what you need on your final exam to pass your class.</h4>
    </div>
</div>
<hr />

<div class="row">
    <div class="form-horizontal col-md-6">
        <div class="col-md-12 form-group">
            @Html.Label("Current Grade", htmlAttributes: new {@class = "control-label col-md-4"} )
            @Html.TextBox("currentGradeBox", "", htmlAttributes: new {@class = "form-control", placeholder = "ex 93.4", @type="number" })
        </div>
        <div class="col-md-12 form-group">
            @Html.Label("Grade Wanted", htmlAttributes: new {@class = "control-label col-md-4" } )
            @Html.TextBox("wantedGradeBox", "", htmlAttributes: new {@class = "form-control", placeholder = "ex 99.6", @type="number"})
        </div>
        <div class="col-md-12 form-group">
            @Html.Label("Final Weight", htmlAttributes: new {@class = "control-label col-md-4" } )
            @Html.TextBox("finalWeightBox", "", htmlAttributes: new {@class = "form-control", placeholder = "ex 20", @type="number" })
        </div>
        <div class="btn btn-primary col-md-4 col-md-offset-1" id="submitButton">Submit</div>
        <div class="col-md-11 col-md-offset-1 add-margin-top">
            <strong><u>Instructions</u></strong>
            <p>1. Enter the grade you currently have in your course.</p>
            <p>2. Enter the grade that you want to get in your course.</p>
            <p>3. Enter the weight of your final exam.</p>
        </div>
    </div>
    <div class="col-md-6" id="resultsSection" hidden>
        <h4>Grade needed on final to get <span id="gradeWantedLabel"></span> in your course:</h4>
        <hr />
        <h4>You need to get <span id="gradeNeededLabel"></span>% or better.</h4>
        <h5 id="extraCreditNeededLabel" class="text-info" hidden>Looks like this score isn't possible without extra credit, sorry!</h5>
    </div>
</div>

<script>
    $('#submitButton').click(function () {
        var currentGrade = parseFloat($('#currentGradeBox').val());
        var gradeWanted = parseFloat($('#wantedGradeBox').val());
        var weight = parseFloat($('#finalWeightBox').val());
        $.ajax({
            url: "/Home/GetFinalGradeNeeded",
            type: "GET",
            datatype: "JSON",
            data: { currentGrade: currentGrade, gradeWanted: gradeWanted, finalWeight: weight },
            success: function (data) {
                var gradeWanted = parseFloat($('#wantedGradeBox').val(), 10);
                $('#gradeWantedLabel').html(gradeWanted + "%").addClass("text-primary");
                var gradeNeeded = parseFloat(data['gradeNeeded'], 10);
                if (gradeNeeded < 0) {
                    $('#gradeNeededLabel').html("0");
                }
                else {
                    $('#gradeNeededLabel').html(gradeNeeded.toFixed(2));
                }
                if (parseInt(data['gradeNeeded'], 10) > 100) {
                    $('#gradeNeededLabel').removeClass("text-primary");
                    $('#gradeNeededLabel').addClass("text-danger");
                    $('#extraCreditNeededLabel').show();
                }
                else {
                    $('#gradeNeededLabel').removeClass("text-danger");
                    $('#gradeNeededLabel').addClass("text-primary");
                    $('#extraCreditNeededLabel').hide();
                }
                // Show the results section after it's been populated.
                $('#resultsSection').show();
            },
            error: function (data) {
                alert("Error");
            }
        });

    })
</script>

GradeTracker/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    ViewBag.ApplicationName = "Personal Gradebook";
    }

<div class="jumbotron">
    <p class="lead">@ViewBag.Applicationname is a <strong>free</strong> grade tracking application for students.</p>
    <a href="@Url.Action("LearnMore", "Home")" class="btn btn-primary">Learn More</a>
    <a href="@Url.Action("Register", "Account")" class="btn btn-primary">Create Account</a>
</div>

<div class="row">
    <div class="col-md-4 text-center">
        <h3>Grade Tracking</h3>
        <h5>Track your assignments, exams, projects and grades for each course.</h5>
    </div> <!-- END "col-md-4" -->

    <div class="col-md-4 text-center">
        <h3><a href="@Url.Action("FinalGradeCalculator", "Home")">Final Grade Calculator</a></h3>
        <h5>Calculate the grades you need on your finals to pass your classes.</h5>
    </div> <!-- END "col-md-4" -->

    <div class="col-md-4 text-center">
        <h3>Detailed Grade Information</h3>
        <h5>Set up grade weight categories for accurate weighted grade calculation.</h5>
    </div> <!-- END "col-md-4" -->

 </div> <!-- END "row" -->

GradeTracker/Views/Home/LearnMore.cshtml
@{
    ViewBag.Title = "LearnMore";
}
<link href="~/Scripts/fancybox/source/jquery.fancybox.css" rel="stylesheet" />
<script src="~/Scripts/fancybox/source/jquery.fancybox.pack.js"></script>
<div class="jumbotron">
    <div class="row">
        <div class="col-md-3">
            <img src="~/Images/logo.png" />
        </div>
        <div class="col-lg-6 text-center">
            <h3 class="add-margin-left">Personal gradebook is a 100% free <br />grade tracking web application for students.</h3>
            <a href="@Url.Action("Register", "Account")"class="btn btn-primary text-center">Join Today!</a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-4 text-center">
        <h4 class="text-info">View/Add Current and Past Semesters</h4>
        <a class="fancybox img-thumbnail display-clickme" rel="group" href="~/Images/Screenshots/SemesterListScreen.png"><img src="~/Images/Screenshots/SemesterListScreenThumb.png" alt="" /></a>
        <ul class="list-text" style="padding-top: 10px;">
            <li>Add Current and Past Semesters</li>
            <li>Keep Track of Old Semester Grades</li>
            <li>View GPA of Each Semester</li>
        </ul>
    </div>
    <div class="col-lg-4 text-center">
        <h4 class="text-info">View/Add Courses To Each Semester</h4>
        <a class="fancybox img-thumbnail display-clickme" rel="group" href="~/Images/Screenshots/CourseListScreen.png"><img src="~/Images/Screenshots/CourseListScreenThumb.png" alt="" /></a>
        <ul class="list-text" style="padding-top: 10px;">
            <li>Add Courses To Each Semester</li>
            <li>View Multiple Course Grades At Once</li>
            <li>Keep Track of Currently Enrolled Courses</li>
        </ul>
    </div>
    <div class="col-lg-4 text-center">
        <h4 class="text-info">Add Assignments and Weights To Courses</h4>
        <a class="fancybox img-thumbnail display-clickme" rel="group" href="~/Images/Screenshots/SpecificCourseScreen.png"><img src="~/Images/Screenshots/SpecificCourseScreenThumb.png" alt="" /></a>
        <ul class="list-text" style="padding-top: 10px;">
            <li>Add Assignments/Work Item to Course</li>
            <li>Set Up Grading Weight Categories</li>
            <li>View Current Grade For Each Category</li>
            <li>View Current Weighted Grade</li>
        </ul>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.fancybox').fancybox();
    });
</script>

GradeTracker/Views/Home/Semesters.cshtml
@{
    ViewBag.Title = "Semesters";
}

<h2>Semesters</h2>